
FROM node:22.9

ADD sources.list /etc/apt/
RUN apt update

# Install Playwright, browsers and browser system dependencies
RUN npx -y playwright@1.42.0 install --with-deps

# Set the work directory for the application
WORKDIR /app
 
# Set the environment path to node_modules/.bin
ENV PATH /app/node_modules/.bin:$PATH

# COPY the needed files to the app folder in Docker image
COPY . /app

# Install the dependencies in Node environment
RUN npm install pnpm -g
RUN pnpm install